// Lista completa de esportes para uso em todos os filtros e seletores
export const ESPORTES = [
  'Airsoft',
  'Arco e Flecha',
  'Atletismo',
  'Automobilismo',
  'Badminton',
  'Basquete 🏀',
  'Basquete 3x3',
  'Beisebol ⚾',
  'Biato',
  'Biliar',
  'Bobsled',
  'Bocha',
  'Bodyboard',
  'Cheerleading',
  'Ciclismo',
  'Corrida de Aventura',
  'Corrida de Cavalos 🏇',
  'Corrida de Galgos',
  'Corrida de Montanha',
  'Corrida de Obstáculos',
  'Corrida de Rua',
  'Corrida de Velocidade',
  'Corrida em Trilhas',
  'Corrida Hípica',
  'Criquete',
  'Curling 🥌',
  'Damas',
  'Dança Esportiva',
  'Dardos',
  'Dodgeball',
  'E-Sports 🎮',
  'Escalada',
  'Escalada Indoor',
  'Esgrima',
  'Futebol Americano 🏈',
  'Futebol Australiano',
  'Futebol Canadense',
  'Futebol de Areia',
  'Futebol de Salão',
  'Futebol Society',
  'Futsal',
  'Hóquei no Gelo 🏒',
  'Hóquei Subaquático',
  'Judo',
  'Kabbadi',
  'Karate',
  'Kart',
  'Kickball',
  'Outros',
  'Outros Esportes',
  'Paintball',
  'Parapente',
  'Parkour',
  'Patinação Artística',
  'Patinação de Velocidade',
  'Queimada',
  'Rali',
  'Remo',
  'Rodeio',
  'Rugby',
  'Rugby de Praia',
  'Sepaktakraw',
  'Triatlo',
  'Ultramaratona',
  'Tênis 🎾',
  'Vela',
  'Vôlei',
  'Vôlei de Praia'
];

